# Generated by Django 4.2.15 on 2024-09-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_cartorder_price_alter_cartorderitems_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
    ]
