# Generated by Django 4.2.15 on 2024-09-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_remove_products_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.vendor'),
        ),
    ]
