# Generated by Django 4.2.15 on 2024-09-05 11:49

from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_vendor_date_alter_products_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='Vendor.jpg', upload_to=ecom.models.user_directory_path),
        ),
    ]
