# Generated by Django 4.2.15 on 2024-09-10 09:26

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('ecom', '0010_products_life_products_mfd_products_stock_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
