# Generated by Django 4.2.15 on 2024-09-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_products_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='name',
            field=models.CharField(default='Untitled', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(default='Untitled', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
