# Generated by Django 4.2.15 on 2024-09-10 12:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_alter_products_description_alter_vendor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='specifications',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is the product', null=True),
        ),
    ]
