# Generated by Django 4.2.15 on 2024-09-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
