# Generated by Django 4.2.15 on 2024-10-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_alter_productreview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'processing'), ('shiped', 'Shiped'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
    ]
